name = "TestPackage"
uuid = "b87c9767-6a26-4343-ab08-150e37cb3bee"
authors = ["Chris Janusiewicz"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
